[tool.poetry]
name = "edea_ms"
version = "0.1.0"
description = "EDeA Measurement Server"
authors = ["Elen Eisendle <ln@calcifer.ee>"]
license = "EUPL"
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.85.0"
ormar = {extras = ["orjson"], version = "^0.11.3"}
uvicorn = {extras = ["standard"], version = "^0.18.3"}
databases = "^0.6.1"
aiosqlite = "^0.17.0"
httpx = "^0.23.0"

[tool.poetry.group.dev.dependencies]
pyre-check = "^0.9.16"
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
trio = "^0.21.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
