[tool.poetry]
name = "edea_ms"
version = "0.1.0"
description = "EDeA Measurement Server"
authors = ["Elen Eisendle <ln@calcifer.ee>"]
license = "EUPL"
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.85.1"
ormar = {extras = ["orjson"], version = "^0.12.0"}
uvicorn = {extras = ["standard"], version = "^0.19.0"}
databases = "^0.6.1"
aiosqlite = "^0.17.0"
httpx = "^0.23.0"
alembic = "^1.8.1"
aiofiles = "^22.1.0"
Jinja2 = "^3.1.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
trio = "^0.21.0"
py-spy = "^0.3.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
