[tool.poetry]
name = "edea_ms"
version = "0.1.0"
description = "EDeA Measurement Server"
authors = ["Elen Eisendle <ln@calcifer.ee>"]
license = "EUPLv1.2"
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.89.0"
sqlalchemy = { extras = ["asyncio"], version = "^2.0.0rc1" }
uvicorn = { extras = ["standard"], version = "^0.20.0" }
aiosqlite = "^0.17.0"
httpx = "^0.23.1"
alembic = "^1.9.0"
aiofiles = "^22.1.0"
Jinja2 = "^3.1.2"
cython = { version = "^0.29.32", optional = true }

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
trio = "^0.22.0"
mypy = "^0.991"
pytest-alembic = "^0.9.1"
sqlalchemy = { version = "2.0.0rc1", extras = ["mypy"] }
sourcery-cli = { version = "^1.0.2", optional = true }

[tool.poetry.group.debug]
optional = true

[tool.poetry.group.debug.dependencies]
yappi = "^1.3.6"
py-spy = "^0.3.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]

follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
