"""define measurement column with project_id fk field

Revision ID: e30150fb8f7a
Revises: 3e593fe27d13
Create Date: 2022-10-28 11:19:30.806219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30150fb8f7a'
down_revision = '3e593fe27d13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
